const express = require('express');
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { all, get, run, logAudit } = require('../db');
const roleCheck = require('../middleware/roleCheck');
const { validateBody } = require('../middleware/validateRequest');

const router = express.Router();
const allowedTypes = ['D1', 'D2', 'D3'];

router.get('/', roleCheck(['super_admin', 'legal', 'bdm']), async (req, res) => {
  try {
    const where = [];
    const params = [];

    if (req.user.role === 'bdm') {
      where.push('s.bdm_id = ?');
      params.push(req.user.id);
    }

    const rows = await all(
      `SELECT n.*, m.name AS member_name, u.name AS generated_by_name
       FROM notices n
       JOIN members m ON n.member_id = m.id
       JOIN societies s ON m.society_id = s.id
       JOIN users u ON n.generated_by = u.id
       ${where.length ? `WHERE ${where.join(' AND ')}` : ''}
       ORDER BY n.id DESC`,
      params
    );

    return res.json(rows);
  } catch (error) {
    return res.status(500).json({ message: 'Failed to fetch notices', error: error.message });
  }
});

router.get('/member/:id', roleCheck(['super_admin', 'legal', 'bdm']), async (req, res) => {
  try {
    const { id } = req.params;

    if (req.user.role === 'bdm') {
      const member = await get(
        `SELECT m.id
         FROM members m
         JOIN societies s ON m.society_id = s.id
         WHERE m.id = ? AND s.bdm_id = ?`,
        [id, req.user.id]
      );
      if (!member) {
        return res.status(403).json({ message: 'Forbidden: member is not in your assigned societies' });
      }
    }

    const rows = await all(
      `SELECT n.*, m.name AS member_name, u.name AS generated_by_name
       FROM notices n
       JOIN members m ON n.member_id = m.id
       JOIN users u ON n.generated_by = u.id
       WHERE n.member_id = ?
       ORDER BY n.id DESC`,
      [id]
    );

    return res.json(rows);
  } catch (error) {
    return res.status(500).json({ message: 'Failed to fetch member notices', error: error.message });
  }
});

router.post('/generate', roleCheck(['super_admin', 'legal', 'bdm']), validateBody([
  { field: 'member_id', required: true, type: 'number' },
  { field: 'type', required: true, enum: ['D1', 'D2', 'D3'] },
]), async (req, res) => {
  try {
    const { member_id, type } = req.body;
    if (!member_id || !type) {
      return res.status(400).json({ message: 'member_id and type are required' });
    }

    if (!allowedTypes.includes(type)) {
      return res.status(400).json({ message: 'type must be one of D1, D2, D3' });
    }

    const member = await get(
      `SELECT m.*, s.bdm_id
       FROM members m
       JOIN societies s ON m.society_id = s.id
       WHERE m.id = ?`,
      [member_id]
    );
    if (!member) {
      return res.status(404).json({ message: 'Member not found' });
    }

    if (req.user.role === 'bdm' && Number(member.bdm_id) !== Number(req.user.id)) {
      return res.status(403).json({ message: 'Forbidden: member is not in your assigned societies' });
    }

    const timestamp = Date.now();
    const fileName = `${type}_${member_id}_${timestamp}.pdf`;
    const noticesDir = path.join(__dirname, '..', 'pdf', 'notices');
    fs.mkdirSync(noticesDir, { recursive: true });

    const filePath = path.join(noticesDir, fileName);
    const pdfUrl = `/pdf/notices/${fileName}`;

    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(20).text(`FinioRevive ${type} Notice`, { align: 'center' });
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Member ID: ${member_id}`);
    doc.text(`Member Name: ${member.name}`);
    doc.text(`Notice Type: ${type}`);
    doc.text(`Generated By User ID: ${req.user.id}`);
    doc.text(`Date: ${new Date().toLocaleString()}`);
    doc.moveDown();
    doc.text('This notice is generated under the FinioRevive financial recovery process.');
    doc.end();

    await new Promise((resolve, reject) => {
      stream.on('finish', resolve);
      stream.on('error', reject);
    });

    const result = await run(
      'INSERT INTO notices (member_id, type, generated_by, pdf_url) VALUES (?, ?, ?, ?)',
      [member_id, type, req.user.id, pdfUrl]
    );

    await run('UPDATE members SET status = ? WHERE id = ?', ['legal', member_id]);

    await logAudit(req.user.id, 'GENERATE_NOTICE', 'notices', result.id);
    return res.status(201).json({ id: result.id, pdf_url: pdfUrl });
  } catch (error) {
    return res.status(500).json({ message: 'Failed to generate notice', error: error.message });
  }
});

module.exports = router;
